Adjust fluent-op request
tx-pts-dai/terraform-aws-kubernetes-platform pull request #118
Opened 2024-12-26 09:41 UTC by rbapst-tamedia

Because of alert.
Operator uses 30MiB with max=37 on last 2 days

## Description
Adapt request on what is needed

## Motivation and Context
We got alert that:

[[prod-discovery,production-discovery] Average RAM usage of fluent-operator is significantly higher than its request](https://tx-pts-dai.pagerduty.com/incidents/Q0OJBVGD4OE9YU?utm_campaign=channel&utm_source=slack)

## Breaking Changes
- None
- 
## How Has This Been Tested?
- [ ] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [ ] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [ ] I have executed `pre-commit run -a` on my pull request

2024-12-27 07:35 UTC, swibrow requested changes
I seen its in draft but I'd recommend these changes.

2024-12-27 07:35 UTC, swibrow commented on files/helm/fluent-operator/common.yaml
> +      memory: 60Mi
remove limits, it mostly causes issues. Its better to monitor usage and adapt accordingly

2024-12-27 07:35 UTC, swibrow commented on files/helm/fluent-operator/common.yaml
> +      memory: 40Mi
make it 100Mi and this should be a non issue again

2024-12-27 07:35 UTC, swibrow commented on files/helm/fluent-operator/common.yaml
> +      cpu: 100m
also remove limits, kubelet can limit at the node level

2024-12-27 11:32 UTC, swibrow commented
Sadly they set resource values:
https://github.com/fluent/fluent-operator/blob/master/charts/fluent-operator/values.yaml#L44-L50

This is normally not a good idea to add in the defaults...

2024-12-27 14:53 UTC, rbapst-tamedia commented
> Sadly they set resource values: https://github.com/fluent/fluent-operator/blob/master/charts/fluent-operator/values.yaml#L44-L50
> 
> This is normally not a good idea to add in the defaults...

Yes, I just saw it :-(

Looks to work by setting `limits.cpu:` and `limits.memory:`

2024-12-31 08:12 UTC, swibrow approved these changes

2025-01-03 15:36 UTC, swibrow requested changes
Can you set 100m 200Mi to be safe?

2025-01-03 15:36 UTC, swibrow commented on files/helm/fluent-operator/common.yaml
> +      memory:
lets set values here. its too much black magic and not so clear without understanding how yaml handles no value maps

2025-01-17 05:58 UTC, swibrow approved these changes

2025-01-17 05:59 UTC, swibrow commented
Will merge since its burning credits

2025-01-17 05:59 UTC, merged