fix: create spot instance service-linked role for Karpenter
tx-pts-dai/terraform-aws-kubernetes-platform pull request #14
Opened 2024-04-12 14:34 UTC by sgametrio

2024-04-15 08:34 UTC, swibrow requested changes
Create the linked roles out of the module. I had the idea to create a bootstrap module that managed the required settings per account.

I guess you tried to deploy to a new account so you had issues with the instance profile, but it's not required once the service linked roles are created.

2024-04-15 08:34 UTC, swibrow commented on main.tf
> +  create_instance_profile         = true
Karpenter creates instance profiles itself so this should be disabled by default

2024-04-15 08:34 UTC, swibrow commented on main.tf
> +resource "aws_iam_service_linked_role" "spot" {
Can only have one per account so should not be in this module.

2024-04-15 08:34 UTC, swibrow commented on main.tf
> +resource "aws_iam_service_linked_role" "spot_fleet" {
Same here

2024-04-15 09:03 UTC, sgametrio commented
@swibrow Thanks for the feedback. Yes I tried running this in the ATM Staging account. I will update the PR to explicit the dependencies that this module needs in order to run with no issues.

I'm good with an external bootstrap module.

2024-04-16 08:26 UTC, sgametrio commented
Closed in favor of #15

2024-04-16 08:26 UTC, closed without merging